#!/bin/bash
set -e
start_pserver() {
    paddle pserver \
      --port=$PADDLE_INIT_PORT \
      --ports_num=$PADDLE_INIT_PORTS_NUM \
      --ports_num_for_sparse=$PADDLE_INIT_PORTS_NUM_FOR_SPARSE \
      --nics=$NICES \
      --comment=paddle_process_k8s \
      --num_gradient_servers=$PADDLE_INIT_NUM_GRADIENT_SERVERS
}

start_trainer() {
    python /root/k8s_tools.py wait_pods_running paddle-job=${PADDLE_JOB_NAME}-pserver ${PSERVERS}
    python /root/k8s_tools.py wait_pods_running paddle-job=${PADDLE_JOB_NAME}-trainer ${TRAINERS}
    export PADDLE_INIT_PSERVERS=$(python /root/k8s_tools.py fetch_pserver_ips)
    export PADDLE_INIT_TRAINER_ID=$(python /root/k8s_tools.py fetch_trainer_id)

    rm -rf /root/trainer
    cp -rf $TRAINER_PACKAGE /root/trainer
    cd /root/trainer
    export PYTHONPATH=/root/trainer:$PYTHONPATH
    ${ENTRY_POINT}
}

usage() {
    echo "usage: paddle_k8s [<args>]:"
    echo "  start_trainer     Start a trainer process"
    echo "  start_pserver     Start a pserver process"
}

case "$1" in
    start_pserver)
        start_pserver
        ;;
    start_trainer)
        start_trainer
        ;;
    --help)
        usage
        ;;
    *)
        usage
        ;;
esac
